//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterestRateCalculation.VilibidViliborService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.lb.lt/VilibidVilibor", ConfigurationName="VilibidViliborService.VilibidViliborSoap")]
    public interface VilibidViliborSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.lb.lt/VilibidVilibor/getVilibRateTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode getVilibRateTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.lb.lt/VilibidVilibor/getVilibRateTypes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> getVilibRateTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.lb.lt/VilibidVilibor/getLatestVilibRate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        decimal getLatestVilibRate(string RateType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.lb.lt/VilibidVilibor/getLatestVilibRate", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> getLatestVilibRateAsync(string RateType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.lb.lt/VilibidVilibor/getVilibRate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        decimal getVilibRate(string RateType, string Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.lb.lt/VilibidVilibor/getVilibRate", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> getVilibRateAsync(string RateType, string Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.lb.lt/VilibidVilibor/getVilibRatesByDate_XmlString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getVilibRatesByDate_XmlString(string Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.lb.lt/VilibidVilibor/getVilibRatesByDate_XmlString", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getVilibRatesByDate_XmlStringAsync(string Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.lb.lt/VilibidVilibor/getVilibRatesByRateType_XmlString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getVilibRatesByRateType_XmlString(string RateType, string DateLow, string DateHigh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.lb.lt/VilibidVilibor/getVilibRatesByRateType_XmlString", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getVilibRatesByRateType_XmlStringAsync(string RateType, string DateLow, string DateHigh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.lb.lt/VilibidVilibor/getVilibRatesByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode getVilibRatesByDate(string Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.lb.lt/VilibidVilibor/getVilibRatesByDate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> getVilibRatesByDateAsync(string Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.lb.lt/VilibidVilibor/getVilibRatesByRateType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode getVilibRatesByRateType(string RateType, string DateLow, string DateHigh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.lb.lt/VilibidVilibor/getVilibRatesByRateType", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> getVilibRatesByRateTypeAsync(string RateType, string DateLow, string DateHigh);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VilibidViliborSoapChannel : InterestRateCalculation.VilibidViliborService.VilibidViliborSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VilibidViliborSoapClient : System.ServiceModel.ClientBase<InterestRateCalculation.VilibidViliborService.VilibidViliborSoap>, InterestRateCalculation.VilibidViliborService.VilibidViliborSoap {
        
        public VilibidViliborSoapClient() {
        }
        
        public VilibidViliborSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VilibidViliborSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VilibidViliborSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VilibidViliborSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode getVilibRateTypes() {
            return base.Channel.getVilibRateTypes();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> getVilibRateTypesAsync() {
            return base.Channel.getVilibRateTypesAsync();
        }
        
        public decimal getLatestVilibRate(string RateType) {
            return base.Channel.getLatestVilibRate(RateType);
        }
        
        public System.Threading.Tasks.Task<decimal> getLatestVilibRateAsync(string RateType) {
            return base.Channel.getLatestVilibRateAsync(RateType);
        }
        
        public decimal getVilibRate(string RateType, string Date) {
            return base.Channel.getVilibRate(RateType, Date);
        }
        
        public System.Threading.Tasks.Task<decimal> getVilibRateAsync(string RateType, string Date) {
            return base.Channel.getVilibRateAsync(RateType, Date);
        }
        
        public string getVilibRatesByDate_XmlString(string Date) {
            return base.Channel.getVilibRatesByDate_XmlString(Date);
        }
        
        public System.Threading.Tasks.Task<string> getVilibRatesByDate_XmlStringAsync(string Date) {
            return base.Channel.getVilibRatesByDate_XmlStringAsync(Date);
        }
        
        public string getVilibRatesByRateType_XmlString(string RateType, string DateLow, string DateHigh) {
            return base.Channel.getVilibRatesByRateType_XmlString(RateType, DateLow, DateHigh);
        }
        
        public System.Threading.Tasks.Task<string> getVilibRatesByRateType_XmlStringAsync(string RateType, string DateLow, string DateHigh) {
            return base.Channel.getVilibRatesByRateType_XmlStringAsync(RateType, DateLow, DateHigh);
        }
        
        public System.Xml.XmlNode getVilibRatesByDate(string Date) {
            return base.Channel.getVilibRatesByDate(Date);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> getVilibRatesByDateAsync(string Date) {
            return base.Channel.getVilibRatesByDateAsync(Date);
        }
        
        public System.Xml.XmlNode getVilibRatesByRateType(string RateType, string DateLow, string DateHigh) {
            return base.Channel.getVilibRatesByRateType(RateType, DateLow, DateHigh);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> getVilibRatesByRateTypeAsync(string RateType, string DateLow, string DateHigh) {
            return base.Channel.getVilibRatesByRateTypeAsync(RateType, DateLow, DateHigh);
        }
    }
}
